import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import {GoPerson} from 'react-icons/go'
import {BsCart4} from 'react-icons/bs'

export default function Layout({title, children}: any) {
  return (
    <>
    <Head>
      <title>{title? title + ' - E-Commerce' : 'E-Commerce'}</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico'/>
    </Head>
    <div className='flex min-h-screen flex-col justify-between bg-[#ebeced]'>
      <header>
        <nav className='flex h-16 px-4 items-center justify-between shadow-md bg-[#ffffff]'>
          <div className='flex items-center bg-[#e7131a] h-full'>
          <Link href='/'>
            <a className='text-lg font-bold px-2'>E-Commerce</a>
          </Link>
          </div>
          <div className='flex items-center font-bold'>
            <Link href='/cart'>
              <a className='p-8'><GoPerson className='scale-[200%]'/></a>
            </Link>
            <Link href='/Login'>
              <a className='p-8 pr-10'>
                <BsCart4 className='scale-[200%]'/>
              </a>
            </Link>
          </div>
        </nav>
      </header>
      <main className='container m-auto mt-4 px-4'>
        {children}
      </main>
      <footer className='flex h-10 justify-center items-center shadow-inner'>
        <p>Ecommerce</p>
      </footer>
    </div>
    </>
  )
}
